name 'post-upload'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures post-upload'
long_description 'Installs/Configures post-upload'
version '0.1.0'
